### ISSUE TITLE
How can change port?

### ISSUE THREAD

**Issue by johnfelipe** [NYPL/transcript-editor#85]
I need change port to 3016, pls share me path and file to do that
tnks

**Comment by beefoo** [comment]
Sure, you can run `rails s -p 3016` or append the following to `./Rakefile`:

```
task :server do
  `bundle exec rails s -p 3016`
end
```

**Comment by johnfelipe** [comment]
felipe@felipeurrego:~/transcript-editor$ cat ./Rakefile
	# Add your own tasks in files placed in lib/tasks ending in .rake,
	# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

	require File.expand_path('../config/application', __FILE__)

	Rails.application.load_tasks

	task :server do
	  `bundle exec rails s -p 3016`
	end

and this is show error

felipe@felipeurrego:~/transcript-editor$ rails s
=> Booting WEBrick
=> Rails 4.2.5 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
[2016-07-15 07:13:44] INFO  WEBrick 1.3.1
[2016-07-15 07:13:44] INFO  ruby 2.1.2 (2014-05-08) [i686-linux]
Exiting
/home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/socket.rb:206:in `bind': Address already in use - bind(2) for 0.0.0.0:3000 (Errno::EADDRINUSE)
        from /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/socket.rb:206:in `listen'
        from /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/socket.rb:461:in `block in tcp_server_sockets'
        from /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/socket.rb:232:in `each'
        from /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/socket.rb:232:in `foreach'
        from /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/socket.rb:459:in `tcp_server_sockets'
        from /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/utils.rb:75:in `create_listeners'
        from /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/server.rb:132:in `listen'
        from /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/server.rb:113:in `initialize'
        from /home/felipe/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/webrick/httpserver.rb:45:in `initialize'
        from /home/felipe/.rvm/gems/ruby-2.1.2/gems/rack-1.6.4/lib/rack/handler/webrick.rb:31:in `new'
        from /home/felipe/.rvm/gems/ruby-2.1.2/gems/rack-1.6.4/lib/rack/handler/webrick.rb:31:in `run'
        from /home/felipe/.rvm/gems/ruby-2.1.2/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
        from /home/felipe/.rvm/gems/ruby-2.1.2/gems/railties-4.2.5/lib/rails/commands/server.rb:80:in `start'
        from /home/felipe/.rvm/gems/ruby-2.1.2/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:80:in `block in server'
        from /home/felipe/.rvm/gems/ruby-2.1.2/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from /home/felipe/.rvm/gems/ruby-2.1.2/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `server'
        from /home/felipe/.rvm/gems/ruby-2.1.2/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /home/felipe/.rvm/gems/ruby-2.1.2/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'

**Comment by beefoo** [comment]
Instead of `rails s`, run `rake server` and see if that works

**Comment by johnfelipe** [comment]
felipe@felipeurrego:~/transcript-editor$ rake server
	[2016-07-15 09:39:21] INFO  WEBrick 1.3.1
	[2016-07-15 09:39:21] INFO  ruby 2.1.2 (2014-05-08) [i686-linux]
	[2016-07-15 09:39:21] INFO  WEBrick::HTTPServer#start: pid=19434 port=3016

But not work with real ip

http://181.135.20.181:3016/

works with `rails s -b 0.0.0.0 -p 3016`

how can fix that localhost to 0.0.0.0?

**Comment by beefoo** [comment]
What happens if you change the `./Rakefile` code to:

```
task :server do
  `bundle exec rails s -b 0.0.0.0 -p 3016`
end
```
