### ISSUE TITLE
voicebase support

### ISSUE THREAD

**Issue by johnfelipe** [NYPL/transcript-editor#88]
curl https://apis.voicebase.com/v2-beta/media/$MEDIA_ID/transcripts/latest \
    --header "Authorization: Bearer $TOKEN" \
    --header "Accept: text/srt"

I need continue my research, voicebase service is possible with srt

Tnks

**Comment by johnfelipe** [comment]
How can convert my srt voicebase file to WebVTT format

TNKS

**Comment by johnfelipe** [comment]
@beefoo do u can help me with this...

**Comment by beefoo** [comment]
I believe [this gem](https://github.com/opencoconut/webvtt-ruby) should be able to do that [conversion](https://github.com/opencoconut/webvtt-ruby#converting-from-srt) from SRT to WebVTT.  The gem is already included in the app, so the code should be as simple as:

```
webvtt = WebVTT.convert_from_srt("path/sub.srt", "path/sub.vtt")
puts webvtt.to_webvtt
```

**Comment by johnfelipe** [comment]
Hi bro this is error, how solved?

	felipe@felipeurrego:~/transcript-editor$ rake transcripts:load['transcribeditor','transcripts_seeds.csv']
	Retrieved 1 rows from file
	  Vendor Load (1.7ms)  SELECT  "vendors".* FROM "vendors" WHERE "vendors"."uid" = $1 LIMIT 1  [["uid", "felipeurrego"]]
	  Collection Load (1.8ms)  SELECT  "collections".* FROM "collections" WHERE "collections"."uid" IS NULL LIMIT 1
	  Transcript Load (2.3ms)  SELECT  "transcripts".* FROM "transcripts" WHERE "transcripts"."uid" = $1 LIMIT 1  [["uid", "ramiriqui"]]
	   (0.8ms)  BEGIN
	  Transcript Exists (1.4ms)  SELECT  1 AS one FROM "transcripts" WHERE "transcripts"."uid" = 'ramiriqui' LIMIT 1
	  SQL (3.1ms)  INSERT INTO "transcripts" ("uid", "title", "description", "audio_url", "vendor_id", "vendor_identifier", "batch_id", "project_uid", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"  [["uid", "ramiriqui"], ["title", "Demo Ramiriqui"], ["description", "Demo presentado para el mcpio de ramiriqui"], ["audio_url", "https://drive.google.com/open?id=0B5b2y2kCFpKoUEJyZWxYRUZSV2s"], ["vendor_id", nil], ["vendor_identifier", "1017133566"], ["batch_id", "transcripts_seeds.csv"], ["project_uid", "transcribeditor"], ["created_at", "2016-10-27 17:10:45.031416"], ["updated_at", "2016-10-27 17:10:45.031416"]]
	   (1.1ms)  ROLLBACK
	rake aborted!
	ActiveRecord::StatementInvalid: PG::NotNullViolation: ERROR:  null value in column "vendor_id" violates not-null constraint
	DETAIL:  Failing row contains (2, ramiriqui, Demo Ramiriqui, Demo presentado para el mcpio de ramiriqui, null, https://drive.google.com/open?id=0B5b2y2kCFpKoUEJyZWxYRUZSV2s, null, 0, null, 1017133566, 0, 0, null, 0, 0, 0, transcripts_seeds.csv, null, null, 2016-10-27 17:10:45.031416, 2016-10-27 17:10:45.031416, [], transcribeditor, 0, 0, 0, 0, 1, 0, 0, 0, 1).
	: INSERT INTO "transcripts" ("uid", "title", "description", "audio_url", "vendor_id", "vendor_identifier", "batch_id", "project_uid", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:192:in `exec_insert'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/relation.rb:64:in `insert'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/persistence.rb:524:in `_create_record'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/counter_cache.rb:139:in `_create_record'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/locking/optimistic.rb:75:in `_create_record'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/attribute_methods/dirty.rb:132:in `_create_record'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/callbacks.rb:306:in `block in _create_record'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/callbacks.rb:306:in `_create_record'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/timestamp.rb:57:in `_create_record'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/persistence.rb:504:in `create_or_update'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/callbacks.rb:302:in `block in create_or_update'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/callbacks.rb:302:in `create_or_update'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/persistence.rb:120:in `save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/validations.rb:37:in `save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/attribute_methods/dirty.rb:21:in `save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:286:in `block in save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:285:in `save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/active_record_helper.rb:26:in `block in save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent.rb:574:in `with_database_metric_name'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/active_record_helper.rb:25:in `save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/persistence.rb:252:in `block in update'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/persistence.rb:250:in `update'
	/home/felipe/transcript-editor/lib/tasks/transcripts.rake:92:in `block (3 levels) in <top (required)>'
	/home/felipe/transcript-editor/lib/tasks/transcripts.rake:70:in `each'
	/home/felipe/transcript-editor/lib/tasks/transcripts.rake:70:in `block (2 levels) in <top (required)>'
	/home/felipe/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	/home/felipe/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
	PG::NotNullViolation: ERROR:  null value in column "vendor_id" violates not-null constraint
	DETAIL:  Failing row contains (2, ramiriqui, Demo Ramiriqui, Demo presentado para el mcpio de ramiriqui, null, https://drive.google.com/open?id=0B5b2y2kCFpKoUEJyZWxYRUZSV2s, null, 0, null, 1017133566, 0, 0, null, 0, 0, 0, transcripts_seeds.csv, null, null, 2016-10-27 17:10:45.031416, 2016-10-27 17:10:45.031416, [], transcribeditor, 0, 0, 0, 0, 1, 0, 0, 0, 1).
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:192:in `exec_insert'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/relation.rb:64:in `insert'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/persistence.rb:524:in `_create_record'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/counter_cache.rb:139:in `_create_record'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/locking/optimistic.rb:75:in `_create_record'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/attribute_methods/dirty.rb:132:in `_create_record'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/callbacks.rb:306:in `block in _create_record'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/callbacks.rb:306:in `_create_record'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/timestamp.rb:57:in `_create_record'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/persistence.rb:504:in `create_or_update'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/callbacks.rb:302:in `block in create_or_update'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:117:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:505:in `call'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activesupport-4.2.5/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/callbacks.rb:302:in `create_or_update'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/persistence.rb:120:in `save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/validations.rb:37:in `save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/attribute_methods/dirty.rb:21:in `save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:286:in `block in save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:285:in `save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/active_record_helper.rb:26:in `block in save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent.rb:574:in `with_database_metric_name'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/newrelic_rpm-3.15.1.316/lib/new_relic/agent/instrumentation/active_record_helper.rb:25:in `save'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/persistence.rb:252:in `block in update'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:220:in `transaction'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	/home/felipe/.rvm/gems/ruby-2.1.2/gems/activerecord-4.2.5/lib/active_record/persistence.rb:250:in `update'
	/home/felipe/transcript-editor/lib/tasks/transcripts.rake:92:in `block (3 levels) in <top (required)>'
	/home/felipe/transcript-editor/lib/tasks/transcripts.rake:70:in `each'
	/home/felipe/transcript-editor/lib/tasks/transcripts.rake:70:in `block (2 levels) in <top (required)>'
	/home/felipe/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	/home/felipe/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
	Tasks: TOP => transcripts:load
	(See full trace by running task with --trace)

**Comment by ClariiD** [comment]
I keep getting the NYPL Github notifications.  Think you can remove me now
:)  Thanks!

Best,
Clarisa

**Comment by beefoo** [comment]
I believe you're missing a value for the "vendor" column in the .csv file.  The value should be `webvtt` if you are loading your own .vtt files

**Comment by johnfelipe** [comment]
I do this

	cd transcript-editor/
	cd /home/felipe/transcript-editor/project/transcribeditor/transcripts
	mkdir srttowebvtt

and

	irb
	2.1.2 :001 > 


	require "webvtt"


	webvtt = WebVTT.convert_from_srt("/home/felipe/transcript-editor/project/transcribeditor/transcripts/srttowebvtt/ramiriquiboyaca2016.srt", "/home/felipe/transcript-editor/project/transcribeditor/transcripts/srttowebvtt/ramiriquiboyaca2016.vtt")


	puts webvtt.to_webvtt

i exit

	cp /home/felipe/transcript-editor/project/transcribeditor/transcripts/srttowebvtt/ramiriquiboyaca2016.vtt /home/felipe/transcript-editor/project/transcribeditor/transcripts/webvtt


	nano /home/felipe/transcript-editor/project/transcribeditor/data/transcripts_seeds.csv

i put this in csv file

	uid,title,description,url,audio_url,image_url,collection,vendor,vendor_identifier,notes
	ramiriqui,Demo Ramiriqui,Demo presentado para el mcpio de ramiriqui,,https://drive.google.com/open?id=0B5b2y2kCFpKoUEJyZWxYRUZSV2s,,pruebas,webvtt,ramiriquiboyaca2016.vtt,

and

	rake transcripts:load['transcribeditor','transcripts_seeds.csv']
	rake webvtt:read['transcribeditor']
	rake project:load['transcribeditor']

My test ip is

http://181.142.77.108:3020/

But nothing show up

What missing?

**Comment by johnfelipe** [comment]
Hi again, bro, what missing?

**Comment by beefoo** [comment]
Can you tell me what you see in your database?  Did the `rake webvtt:read['transcribeditor']` run successfully?  If so, you should see the transcript's lines in the table `transcript_lines`, if not, did you get any error when you ran any of the tasks?

**Comment by johnfelipe** [comment]
felipe@felipeurrego:~/transcript-editor/project/transcribeditor/transcripts$ rake webvtt:read['transcribeditor']
	(in /home/felipe/transcript-editor)
	  Vendor Load (1.7ms)  SELECT  "vendors".* FROM "vendors" WHERE "vendors"."uid" = $1 LIMIT 1  [["uid", "webvtt"]]
	  Transcript Load (4.3ms)  SELECT "transcripts".* FROM "transcripts" INNER JOIN "collections" ON "collections"."id" = "transcripts"."collection_id" WHERE (transcripts.vendor_id = 2 AND transcripts.lines <= 0 AND collections.vendor_identifier != '' AND transcripts.vendor_identifier != '' AND transcripts.project_uid = 'transcribeditor')
	Retrieved 0 transcripts from collections with webvtt as its vendor that are empty
	  Transcript Load (2.8ms)  SELECT  "transcripts".* FROM "transcripts" INNER JOIN "collections" ON "collections"."id" = "transcripts"."collection_id" WHERE (transcripts.vendor_id = 2 AND transcripts.lines <= 0 AND collections.vendor_identifier != '' AND transcripts.vendor_identifier != '' AND transcripts.project_uid = 'transcribeditor')  ORDER BY "transcripts"."id" ASC LIMIT 1000

![vendor](https://cloud.githubusercontent.com/assets/428820/19973981/e61c92ea-a1b4-11e6-9caf-ad285fe60945.png)
and
![vtt](https://cloud.githubusercontent.com/assets/428820/19974002/facfcf9a-a1b4-11e6-86a6-7e7113a294d6.png)

**Comment by beefoo** [comment]
I think it's because you need to create a collection "pruebas" as well. See [this section](https://github.com/NYPL/transcript-editor#making-collectionsgroups).  `collections_seeds.csv` might look like this:

```
uid,title,description,url,image_url,vendor,vendor_identifier
pruebas,Pruebas,,,,webvtt,pruebas
```

Then run `rake collections:load['transcribeditor','collections_seeds.csv']`

**Comment by johnfelipe** [comment]
Hi bro, its working in shell but 
http://181.142.77.108:3020/transcripts/ramiriqui

Is not working
How solved

**Comment by beefoo** [comment]
It looks like the time codings did not read properly.  Can you attach the .vtt file?

**Comment by johnfelipe** [comment]
This is voicebase url: https://app.voicebase.com/autonotes/private_detail/31599505/hash=bJWaaW1qZm2Wb2ibx2GVnGuPnJplmWZsmZnDkZprxJdmm55nmJtuaW2Ybpqb?vbt=0

I download transcript:

![srt](https://cloud.githubusercontent.com/assets/428820/19991771/4e7a33e6-a206-11e6-8b08-71b4c095e8ac.png)

This is process for convert into vtt file:

	gem install webvtt-ruby
	irb
	2.1.2 :001 > 


	require "webvtt"


	webvtt = WebVTT.convert_from_srt("/home/felipe/transcript-editor/project/transcribeditor/transcripts/srttowebvtt/ramiriquiboyaca2016.srt", "/home/felipe/transcript-editor/project/transcribeditor/transcripts/srttowebvtt/ramiriquiboyaca2016.vtt")


	puts webvtt.to_webvtt

And this is file:

http://pastebin.com/jEvfHjuB

This is audio url: https://drive.google.com/open?id=0B5b2y2kCFpKoUEJyZWxYRUZSV2s

Stay alert for solve this issue

**Comment by johnfelipe** [comment]
@beefoo any advance?

**Comment by johnfelipe** [comment]
@beefoo https://github.com/NYPL/transcript-editor/issues/88#issuecomment-258252879, pls help me im waiting

**Comment by johnfelipe** [comment]
@beefoo pls tell me about https://github.com/NYPL/transcript-editor/issues/88#issuecomment-258252879, im still waiting

**Comment by beefoo** [comment]
Hi sorry for the delay-- I currently don't officially have time to work on this codebase.  But I looked into the code and I think I found the problem; you might need to format your .srt file differently from what it currently is. For example this line does not convert correctly:

```
00:00:00,00 --> 00:00:11,04
```

But this line does:
```
00:00:00,000 --> 00:00,11.040
```

If you look in the [web-ruby parser](https://github.com/opencoconut/webvtt-ruby/) code on [this line](https://github.com/opencoconut/webvtt-ruby/blob/master/lib/webvtt/parser.rb#L16), you see that the parser expects three decimal places instead of two. 

I suggest you can either edit your .srt files somehow to include 3 decimal places, or branch the web-ruby parser and edit the line I referred to above to this:

```
srt.gsub!(/([0-9]{2}:[0-9]{2}:[0-9]{2})([,])([0-9]{2})/, '\1.\30')
```

After you do that, you should probably start the database from scratch and try again:

```
rake collections:load['transcribeditor','collections_seeds.csv']
rake transcripts:load['transcribeditor','transcripts_seeds.csv']
rake webvtt:read['transcribeditor']
```

**Comment by johnfelipe** [comment]
Hi again, this is all my process and steps, pls give me instructions for solve it:

	cd transcript-editor/

	gem install webvtt-ruby

	cd /home/felipe/.rvm/gems/ruby-2.1.2/gems/webvtt-ruby-0.3.2

	sudo nano /home/felipe/.rvm/gems/ruby-2.1.2/gems/webvtt-ruby-0.3.2/lib/webvtt/parser.rb

	##
		#srt.gsub!(/([0-9]{2}:[0-9]{2}:[0-9]{2})([,])([0-9]{3})/, '\1.\3')
		srt.gsub!(/([0-9]{2}:[0-9]{2}:[0-9]{2})([,])([0-9]{2})/, '\1.\30')

	##

	cd /home/felipe/transcript-editor/project/transcribeditor/transcripts

	mkdir srttowebvtt

	irb

	2.1.2 :001 > 

	require "webvtt"

	webvtt = WebVTT.convert_from_srt("/home/felipe/transcript-editor/project/transcribeditor/transcripts/srttowebvtt/ramiriquiboyaca2016.srt", "/home/felipe/transcript-editor/project/transcribeditor/transcripts/srttowebvtt/ramiriquiboyaca2016.vtt")

	puts webvtt.to_webvtt
	exit

	cp /home/felipe/transcript-editor/project/transcribeditor/transcripts/srttowebvtt/ramiriquiboyaca2016.vtt /home/felipe/transcript-editor/project/transcribeditor/transcripts/webvtt

	nano /home/felipe/transcript-editor/project/transcribeditor/data/transcripts_seeds.csv

	##

	uid,title,description,url,audio_url,image_url,collection,vendor,vendor_identifier,notes
	ramiriqui,Demo Ramiriqui,Demo presentado para el mcpio de ramiriqui,,https://drive.google.com/open?id=0B5b2y2kCFpKoUEJyZWxYRUZSV2s,,pruebas,webvtt,ramiriquiboyaca2016.vtt,


	##

	nano /home/felipe/transcript-editor/project/transcribeditor/data/collections_seeds.csv

	##

	uid,title,description,url,image_url,vendor,vendor_identifier
	pruebas,Pruebas,,,,webvtt,pruebas

	##

	rake collections:load['transcribeditor','collections_seeds.csv']
	rake transcripts:load['transcribeditor','transcripts_seeds.csv']
	rake webvtt:read['transcribeditor']
	rake project:load['transcribeditor']

And is not working

http://181.142.77.108:3020/transcripts/ramiriqui

Stay alert

**Comment by johnfelipe** [comment]
@beefoo or anyone, pls help me for solve that issue and continue
Tnks
Stay alert
